### ISSUE TITLE
Decide whether to use Jekyll or something else to build the website

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/OpenMaine_ForkedFromLA#7]
See requirements:
https://github.com/OpenMaine/OpenMaine_ForkedFromLA/wiki/Requirements

**Comment by shannonmcharg** [comment]
Pros of using Jekyll:
- We can reuse code from other brigades
- Opportunity to partner with Hack for LA
- Uses templates that are easy to fill out for things like projects

Cons of using Jekyll:
- I don't think we have anyone who is an expert in Jekyll (I know just enough to be dangerous)
- Requires hosting on GitHub Pages to build the site, potentially limiting our hosting options

**Comment by shannonmcharg** [comment]
@AmyMcGann Can you add some pros and cons of using whatever you built your version in?

**Comment by congdon** [comment]
I keep forgetting to look at the source of the Jekyll pages, but if it can only be hosted on github, I feel like that's not the right option for us.

I am also concerned about the path for editing the site and whether it might be too complicated for us to commit to. But again, I haven't looked.

(I really apologize for forgetting to look. I really appreciate your work, Shannon.)

**Comment by shannonmcharg** [comment]
I don't care what we build it in.  I was just using the Jekyll site as a shortcut to design the site.

There may be other options for building Jekyll.  Ryan was just saying last week that GitHub pages builds it in addition to hosting it, so we'll need to consider that when picking a hosting option. @rentry Maybe you can explain better than me.

**Comment by rentry** [comment]
@congdon and @shannonmcharg You can host a Jekyll site on literally any web server, anywhere in the world. If the host provider doesn't include a build service, it just requires a manual build instead.

To do the manual process, you build the site locally using `jekyll build`, then convey the resulting `_site` folder to any webhost of your choosing.

You can also use a different build+host service other than GitHub, such as [Netlify](https://www.netlify.com/blog/2015/10/28/a-step-by-step-guide-jekyll-3.0-on-netlify/). But GitHub Pages was created largely to build Jekyll sites.

If you have hosting requirements, it would be helpful to see them.

**Comment by shannonmcharg** [comment]
@rentry I think the primary requirement for hosting is that it will allow us to host project websites under the openmaine.org domain, for example openmaine.org/[projectname].

Here's a sample of the type of project that would need to be hosted. http://portlandbudget.openmaine.org/

**Comment by rentry** [comment]
I see, @shannonmcharg. Since that's mostly on the domain management side, you shouldn't have any trouble there with hosting. You can easily [manage subdomains with GitHub Pages project pages](https://anmonteiro.com/2015/08/custom-subdomains-in-github-project-pages/), if that's what you choose to do.

**Comment by congdon** [comment]
Hi Ryan, Thank you for your help!

We will have code projects, not just web pages. I suppose GitHub pages can probably do client-side JavaScript, but we need server-side stuff. Also I think there are space/storage issues on GitHub. So I don't see GitHub as the best path for us for hosting.

Thanks again!
